version: '2'
services:
  mongodb1:
    container_name: mongodb1
    hostname: mongodb1
    image: mongo
    volumes:
      - ./mongodb/node1:/var/lib/mongodb
    ports:
      - 27017
  mongodb2:
    container_name: mongodb2
    hostname: mongodb2
    image: mongo
    volumes:
      - ./mongodb/node2:/var/lib/mongodb
    ports:
      - 27017
  mongodb3:
    container_name: mongodb3
    hostname: mongodb3
    image: mongo
    volumes:
      - ./mongodb/node3:/var/lib/mongodb
    ports:
      - 27017

