version: '3'

services:
  mongodb01:
    container_name: mongodb01
    image: mongo:latest
    volumes:
      - ./mongodb01:/data/db
    ports:
      - 27017:27017
    command: [mongod, --bind_ip, 0.0.0.0, --replSet, my-mongo-set]
    domainname: mongodb

  mongodb02:
    container_name: mongodb02
    image: mongo:latest
    volumes:
      - ./mongodb02:/data/db
    ports:
      - 27018:27017
    command: [mongod, --bind_ip, 0.0.0.0, --replSet, my-mongo-set]
    domainname: mongodb

  mongodb03:
    container_name: mongodb03
    image: mongo:latest
    volumes:
      - ./mongodb03:/data/db
    ports:
      - 27019:27017
    command: [mongod, --bind_ip, 0.0.0.0, --replSet, my-mongo-set]
    domainname: mongodb

networks:
  default:
    external:
      name: mongodb

